// NOIR — product catalog (22 items) + i18n strings
// Prices in ILS

window.NOIR_PRODUCTS = [
  { id: 'p01', name: { ar: 'معطف صوفي طويل', en: 'Wool Long Coat' }, cat: 'outer', price: 1290, was: 1490, color: 'charcoal', sizes: ['S','M','L','XL'], colors: ['charcoal','clay','olive'], tag: 'new', meta: { ar: 'صوف إيطالي · مقاس عادي', en: 'Italian wool · Regular fit' } },
  { id: 'p02', name: { ar: 'تيشيرت قطن أساسي', en: 'Essential Cotton Tee' }, cat: 'tops', price: 129, color: 'ink', sizes: ['XS','S','M','L','XL'], colors: ['ink','charcoal','sage'], meta: { ar: 'قطن عضوي · 240 جم', en: 'Organic cotton · 240gsm' } },
  { id: 'p03', name: { ar: 'بنطال واسع بحزام', en: 'Pleated Wide Trouser' }, cat: 'bottoms', price: 459, was: 549, color: 'olive', sizes: ['S','M','L'], colors: ['olive','ink','clay'], tag: 'sale', meta: { ar: 'كتان مخلوط · قص واسع', en: 'Linen blend · Wide cut' } },
  { id: 'p04', name: { ar: 'فستان حريري', en: 'Silk Slip Dress' }, cat: 'dresses', price: 689, color: 'rose', sizes: ['XS','S','M','L'], colors: ['rose','ink','blood'], tag: 'lime', meta: { ar: 'حرير 100٪ · ميدي', en: '100% silk · Midi length' } },
  { id: 'p05', name: { ar: 'حذاء جلد كلاسيكي', en: 'Derby Leather Shoe' }, cat: 'shoes', price: 899, color: 'blood', sizes: ['39','40','41','42','43','44'], colors: ['blood','ink','charcoal'], meta: { ar: 'جلد طبيعي مدبوغ', en: 'Vegetable-tanned leather' } },
  { id: 'p06', name: { ar: 'جاكيت دنيم خام', en: 'Raw Denim Jacket' }, cat: 'outer', price: 689, color: 'cobalt', sizes: ['S','M','L','XL'], colors: ['cobalt','ink'], tag: 'new', meta: { ar: 'دنيم 14 أونصة', en: '14oz selvedge denim' } },
  { id: 'p07', name: { ar: 'سويتر كشمير', en: 'Cashmere Crewneck' }, cat: 'tops', price: 970, color: 'cream', sizes: ['S','M','L'], colors: ['cream','mist','olive'], meta: { ar: 'كشمير منغولي', en: 'Mongolian cashmere' } },
  { id: 'p08', name: { ar: 'تنورة بليسيه', en: 'Pleated Midi Skirt' }, cat: 'bottoms', price: 379, color: 'mist', sizes: ['XS','S','M','L'], colors: ['mist','ink','rose'], meta: { ar: 'مايكروفايبر · ميدي', en: 'Microfiber · Midi' } },
  { id: 'p09', name: { ar: 'حذاء رياضي تقني', en: 'Tech Runner Sneaker' }, cat: 'shoes', price: 549, was: 649, color: 'mist', sizes: ['38','39','40','41','42','43'], colors: ['mist','ink'], tag: 'sale', meta: { ar: 'نعل EVA مرن', en: 'EVA cushioning' } },
  { id: 'p10', name: { ar: 'قميص أكسفورد', en: 'Oxford Shirt' }, cat: 'tops', price: 289, color: 'mist', sizes: ['S','M','L','XL'], colors: ['mist','ink','sage'], meta: { ar: 'قطن أكسفورد', en: 'Oxford weave cotton' } },
  { id: 'p11', name: { ar: 'حقيبة كتف جلدية', en: 'Leather Shoulder Bag' }, cat: 'bags', price: 1190, color: 'clay', sizes: ['One'], colors: ['clay','ink','blood'], tag: 'new', meta: { ar: 'جلد بقري كامل', en: 'Full-grain leather' } },
  { id: 'p12', name: { ar: 'نظارة شمسية معدنية', en: 'Metal Frame Sunglasses' }, cat: 'accessories', price: 459, color: 'ink', sizes: ['One'], colors: ['ink','amber'], meta: { ar: 'حماية UV400', en: 'UV400 protection' } },
  { id: 'p13', name: { ar: 'ساعة أوتوماتيك', en: 'Automatic Watch' }, cat: 'accessories', price: 2390, color: 'ink', sizes: ['One'], colors: ['ink','clay'], tag: 'lime', meta: { ar: 'حركة سويسرية', en: 'Swiss movement' } },
  { id: 'p14', name: { ar: 'حزام جلدي', en: 'Leather Belt' }, cat: 'accessories', price: 219, color: 'clay', sizes: ['80','85','90','95'], colors: ['clay','ink','blood'], meta: { ar: 'إبزيم فولاذ', en: 'Steel buckle' } },
  { id: 'p15', name: { ar: 'سترة ركض', en: 'Track Pullover' }, cat: 'tops', price: 389, color: 'sage', sizes: ['S','M','L','XL'], colors: ['sage','ink','charcoal'], meta: { ar: 'بوليستر تقني', en: 'Technical poly' } },
  { id: 'p16', name: { ar: 'بنطال جينز مستقيم', en: 'Straight Jeans' }, cat: 'bottoms', price: 359, color: 'cobalt', sizes: ['28','30','32','34','36'], colors: ['cobalt','ink','mist'], meta: { ar: 'دنيم خام', en: 'Raw denim' } },
  { id: 'p17', name: { ar: 'فستان قميص', en: 'Shirt Dress' }, cat: 'dresses', price: 489, color: 'amber', sizes: ['XS','S','M','L'], colors: ['amber','ink','olive'], meta: { ar: 'تنسيليل · فضفاض', en: 'Tencel · Relaxed' } },
  { id: 'p18', name: { ar: 'بوت جلدي قصير', en: 'Chelsea Boot' }, cat: 'shoes', price: 1090, color: 'ink', sizes: ['40','41','42','43','44'], colors: ['ink','blood'], tag: 'new', meta: { ar: 'جلد لامع', en: 'Polished leather' } },
  { id: 'p19', name: { ar: 'وشاح صوفي', en: 'Wool Scarf' }, cat: 'accessories', price: 249, color: 'cream', sizes: ['One'], colors: ['cream','charcoal','blood'], meta: { ar: 'صوف ميرينو', en: 'Merino wool' } },
  { id: 'p20', name: { ar: 'قميص حريري', en: 'Silk Blouse' }, cat: 'tops', price: 590, was: 690, color: 'rose', sizes: ['XS','S','M','L'], colors: ['rose','ink','sage'], tag: 'sale', meta: { ar: 'حرير شارميوز', en: 'Charmeuse silk' } },
  { id: 'p21', name: { ar: 'حقيبة ظهر تقنية', en: 'Tech Backpack' }, cat: 'bags', price: 689, color: 'charcoal', sizes: ['One'], colors: ['charcoal','ink','olive'], meta: { ar: 'مقاومة للماء', en: 'Water-resistant' } },
  { id: 'p22', name: { ar: 'فستان ميدي مطبوع', en: 'Printed Midi Dress' }, cat: 'dresses', price: 729, color: 'blood', sizes: ['XS','S','M','L'], colors: ['blood','ink','olive'], tag: 'lime', meta: { ar: 'فيسكوز ناعم', en: 'Soft viscose' } },
];

window.NOIR_CATEGORIES = [
  { id: 'all', ar: 'الكل', en: 'All' },
  { id: 'outer', ar: 'معاطف', en: 'Outerwear' },
  { id: 'tops', ar: 'قمصان', en: 'Tops' },
  { id: 'bottoms', ar: 'بناطيل', en: 'Bottoms' },
  { id: 'dresses', ar: 'فساتين', en: 'Dresses' },
  { id: 'shoes', ar: 'أحذية', en: 'Shoes' },
  { id: 'bags', ar: 'حقائب', en: 'Bags' },
  { id: 'accessories', ar: 'إكسسوار', en: 'Accessories' },
];

window.NOIR_I18N = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.shop': 'التسوق',
    'nav.search': 'البحث',
    'nav.bag': 'السلة',
    'nav.account': 'حسابي',
    'hero.tag': 'تشكيلة الموسم · ٢٠٢٦',
    'hero.title1': 'الأناقة',
    'hero.title2': 'بصياغة',
    'hero.title3': 'جديدة',
    'hero.cta': 'تسوّق التشكيلة',
    'hero.cta2': 'استكشف',
    'hero.meta1': 'منتج جديد',
    'hero.meta2': 'شحن مجاني',
    'hero.meta3': 'إرجاع خلال ٣٠ يوم',
    'home.featured': 'الأبرز هذا الأسبوع',
    'home.new': 'وصل حديثاً',
    'home.collections': 'تشكيلات مختارة',
    'home.editorial': 'حكاية الموسم',
    'shop.title': 'تصفّح',
    'shop.search': 'ابحث عن منتج، فئة، لون...',
    'shop.filter': 'فلترة',
    'shop.sort': 'الترتيب',
    'shop.results': 'نتيجة',
    'shop.empty': 'لا توجد نتائج مطابقة',
    'filter.size': 'المقاس',
    'filter.color': 'اللون',
    'filter.price': 'السعر',
    'filter.cat': 'الفئة',
    'filter.apply': 'تطبيق',
    'filter.clear': 'مسح الكل',
    'pd.size': 'اختر المقاس',
    'pd.color': 'اللون',
    'pd.guide': 'دليل المقاسات',
    'pd.fav': 'إضافة للمفضلة',
    'pd.cart': 'أضف إلى السلة',
    'pd.buy': 'اشترِ الآن',
    'pd.desc': 'الوصف',
    'pd.specs': 'التفاصيل',
    'pd.ship': 'الشحن',
    'pd.review': 'التقييمات',
    'pd.story': 'تشكيلة محدودة، صنع يدوي بمواد مختارة بعناية. كل قطعة تعكس مزيجاً متوازناً بين الأناقة الكلاسيكية واللمسة الحديثة، تناسب أسلوب حياتك اليومي.',
    'cart.title': 'سلتي',
    'cart.empty': 'السلة فارغة',
    'cart.empty.sub': 'استكشف التشكيلة وأضف ما يلفت انتباهك',
    'cart.empty.cta': 'ابدأ التسوق',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.ship': 'الشحن',
    'cart.ship.free': 'مجاني',
    'cart.tax': 'الضريبة',
    'cart.total': 'الإجمالي',
    'cart.checkout': 'الدفع',
    'cart.promo': 'كود خصم',
    'wish.title': 'المفضلة',
    'wish.empty': 'لا قطع مفضلة بعد',
    'wish.empty.sub': 'انقر على القلب فوق أي منتج لحفظه هنا',
    'co.title': 'إتمام الشراء',
    'co.step1': 'العنوان',
    'co.step2': 'الشحن',
    'co.step3': 'الدفع',
    'co.step4': 'تأكيد',
    'co.name': 'الاسم الكامل',
    'co.phone': 'الهاتف',
    'co.address': 'العنوان',
    'co.city': 'المدينة',
    'co.zip': 'الرمز البريدي',
    'co.continue': 'متابعة',
    'co.pay': 'ادفع الآن',
    'co.success': 'تم الطلب!',
    'co.success.sub': 'سنرسل لك تفاصيل الشحن على بريدك',
    'co.order': 'رقم الطلب',
    'acc.title': 'حسابي',
    'acc.greet': 'أهلاً',
    'acc.orders': 'طلباتي',
    'acc.address': 'العناوين',
    'acc.payment': 'طرق الدفع',
    'acc.notif': 'الإشعارات',
    'acc.help': 'الدعم',
    'acc.logout': 'تسجيل خروج',
    'login.signin': 'تسجيل الدخول',
    'login.signup': 'إنشاء حساب',
    'login.welcome': 'أهلاً من جديد',
    'login.sub': 'سجّل دخولك للمتابعة',
    'login.email': 'البريد الإلكتروني',
    'login.pass': 'كلمة المرور',
    'login.continue': 'متابعة',
    'login.or': 'أو',
    'login.google': 'متابعة عبر Google',
    'login.apple': 'متابعة عبر Apple',
    'install.title': 'ثبّت تطبيق NOIR',
    'install.sub': 'وصول أسرع وعمل بدون إنترنت',
    'install.btn': 'تثبيت',
    'install.web': 'حمّل التطبيق',
    'install.installing': 'جاري التثبيت',
    'install.opening': 'فتح التطبيق',
    'install.welcome': 'أهلاً بك في NOIR',
    'toast.cart': 'تمت الإضافة للسلة',
    'toast.fav': 'محفوظ في المفضلة',
    'toast.unfav': 'تم الإزالة من المفضلة',
    'toast.lang': 'تم تغيير اللغة',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.save': 'وفّر',
    'common.new': 'جديد',
    'common.sale': 'تخفيض',
    'common.featured': 'مميّز',
    'currency': '₪',
  },
  en: {
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.search': 'Search',
    'nav.bag': 'Bag',
    'nav.account': 'Account',
    'hero.tag': 'Season Drop · 2026',
    'hero.title1': 'Elegance',
    'hero.title2': 'rewritten',
    'hero.title3': 'in motion',
    'hero.cta': 'Shop the drop',
    'hero.cta2': 'Explore',
    'hero.meta1': 'New pieces',
    'hero.meta2': 'Free shipping',
    'hero.meta3': '30-day returns',
    'home.featured': 'Featured this week',
    'home.new': 'Just landed',
    'home.collections': 'Curated edits',
    'home.editorial': 'Season story',
    'shop.title': 'Shop',
    'shop.search': 'Search for product, category, color...',
    'shop.filter': 'Filter',
    'shop.sort': 'Sort',
    'shop.results': 'results',
    'shop.empty': 'No matches',
    'filter.size': 'Size',
    'filter.color': 'Color',
    'filter.price': 'Price',
    'filter.cat': 'Category',
    'filter.apply': 'Apply',
    'filter.clear': 'Clear all',
    'pd.size': 'Select size',
    'pd.color': 'Color',
    'pd.guide': 'Size guide',
    'pd.fav': 'Add to wishlist',
    'pd.cart': 'Add to bag',
    'pd.buy': 'Buy now',
    'pd.desc': 'Description',
    'pd.specs': 'Details',
    'pd.ship': 'Shipping',
    'pd.review': 'Reviews',
    'pd.story': 'A limited edition, handcrafted from carefully selected materials. Every piece balances classic elegance with a modern edge to fit how you actually live.',
    'cart.title': 'Bag',
    'cart.empty': 'Your bag is empty',
    'cart.empty.sub': 'Explore the drop and add what catches your eye',
    'cart.empty.cta': 'Start shopping',
    'cart.subtotal': 'Subtotal',
    'cart.ship': 'Shipping',
    'cart.ship.free': 'Free',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.promo': 'Promo code',
    'wish.title': 'Wishlist',
    'wish.empty': 'No saved pieces yet',
    'wish.empty.sub': 'Tap the heart on any product to save it here',
    'co.title': 'Checkout',
    'co.step1': 'Address',
    'co.step2': 'Shipping',
    'co.step3': 'Payment',
    'co.step4': 'Confirm',
    'co.name': 'Full name',
    'co.phone': 'Phone',
    'co.address': 'Address',
    'co.city': 'City',
    'co.zip': 'Postal code',
    'co.continue': 'Continue',
    'co.pay': 'Pay now',
    'co.success': 'Order placed!',
    'co.success.sub': 'We\'ll email you the shipping details',
    'co.order': 'Order #',
    'acc.title': 'Account',
    'acc.greet': 'Welcome',
    'acc.orders': 'My orders',
    'acc.address': 'Addresses',
    'acc.payment': 'Payment methods',
    'acc.notif': 'Notifications',
    'acc.help': 'Support',
    'acc.logout': 'Sign out',
    'login.signin': 'Sign in',
    'login.signup': 'Sign up',
    'login.welcome': 'Welcome back',
    'login.sub': 'Sign in to continue',
    'login.email': 'Email',
    'login.pass': 'Password',
    'login.continue': 'Continue',
    'login.or': 'or',
    'login.google': 'Continue with Google',
    'login.apple': 'Continue with Apple',
    'install.title': 'Install NOIR',
    'install.sub': 'Faster access, works offline',
    'install.btn': 'Install',
    'install.web': 'Download app',
    'install.installing': 'Installing',
    'install.opening': 'Opening app',
    'install.welcome': 'Welcome to NOIR',
    'toast.cart': 'Added to bag',
    'toast.fav': 'Saved to wishlist',
    'toast.unfav': 'Removed from wishlist',
    'toast.lang': 'Language switched',
    'common.from': 'from',
    'common.to': 'to',
    'common.save': 'Save',
    'common.new': 'New',
    'common.sale': 'Sale',
    'common.featured': 'Featured',
    'currency': '₪',
  }
};
